- task: DotNetCoreCLI@2
  displayName: 'Publish dotnet 5 project'
  inputs:
    command: publish
    publishWebProjects: false
    zipAfterPublish: true
    projects: |
     SamLearnsAzure/SamLearnsAzure.Web2/SamLearnsAzure.Web2.csproj
    arguments: '--configuration ${{parameters.buildConfiguration}} --output $(build.artifactstagingdirectory) --self-contained true --runtime win-x86'