
# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

- task: DotNetCoreCLI@2
  displayName: 'Publish dotnet 5 project'
  inputs:
    command: publish
    publishWebProjects: false
    zipAfterPublish: true
    projects: |
     SamLearnsAzure/SamLearnsAzure.Web2/SamLearnsAzure.Web2.csproj
    arguments: '--configuration ${{parameters.buildConfiguration}} --output $(build.artifactstagingdirectory) --self-contained true --runtime win-x86'